"""Versioned local capture of raw events, task provenance and bounded state.

Every event is retained and classified; inherited task links preserve uncertainty.
Workspace content is deduplicated into local blobs alongside Git references.
Size and time bounds are reported rather than silently hiding partial snapshots.
Verification events carry a post-command manifest association, not proof of an
atomic execution snapshot. The report distinguishes recovery from verification.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, cast

SCHEMA = "xyntetik.shadow.capture.v2"
CAPTURE2_FILE = ".xyntetik/shadow/capture2.jsonl"
BLOBS_DIR = ".xyntetik/shadow/blobs"
THREADS_FILE = ".xyntetik/shadow/threads.json"
JOBS_FILE = ".xyntetik/shadow/jobs.json"

ATTR_SELF = "self"                       # the event is its own origin
ATTR_HEURISTIC = "association_heuristic"  # inherited, not established

# Budgets. The hook gets 10 s from the harness; these keep the snapshot an
# order of magnitude inside that, and every one of them is recorded when it
# bites so a short snapshot is never mistaken for a small workspace.
MAX_FILE_BYTES = 256 * 1024
MAX_TOTAL_BYTES = 4 * 1024 * 1024
MAX_FILES = 200
SNAPSHOT_DEADLINE_S = 3.0
MAX_RAW_BYTES = 64 * 1024

# ---------------------------------------------------------------- provenance

PROV_USER = "user_request"
PROV_NOTIFICATION = "harness_notification"
PROV_REMINDER = "harness_reminder"
PROV_CONTINUATION = "continuation"
PROV_WORKER = "worker_assignment"
PROV_UNKNOWN = "unknown"
PROV_SESSION = "session_event"

# ANCHORED at the start of the text, with \A rather than a search. An earlier
# version searched the first 400 characters, which labelled
# "fix the validation guard\n\n<system-reminder>..." a reminder -- a real request
# with a reminder stapled to its end. The envelope that governs is the one the
# harness put FIRST; anything appended afterwards is decoration on a request.
_NOTIFICATION = re.compile(r"\A\s*<task-notification>", re.I)
_REMINDER = re.compile(r"\A\s*<system-reminder>", re.I)
_LOCAL_CMD = re.compile(r"\A\s*<(command-name|local-command-stdout|command-message)>", re.I)
_CONTINUATION = re.compile(
    r"\A\s*(This session is being continued from a previous conversation|"
    r"Continue the conversation from where it left off|"
    r"Caveat: The messages below were generated by the user while running local commands)",
    re.I)


@dataclass
class Provenance:
    kind: str
    evidence: str
    originating_event_id: str | None = None
    task_id: str | None = None
    attribution: str = ATTR_SELF
    attribution_basis: str = ""
    ownership_uncertain: bool = False
    candidate_task_ids: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {"kind": self.kind, "evidence": self.evidence,
                "originating_event_id": self.originating_event_id,
                "task_id": self.task_id,
                "attribution": self.attribution,
                "attribution_basis": self.attribution_basis,
                "ownership_uncertain": self.ownership_uncertain,
                "candidate_task_ids": self.candidate_task_ids}


def classify(text: str, *, payload: dict[str, Any] | None = None,
             event: str = "prompt") -> Provenance:
    """Label where an event came from. Never drops and never rewrites the text.

    Order matters: a prompt can carry a reminder appended to a real request, and
    the governing label is the one at the START of the text, because that is
    what the harness put there. A request with a reminder stapled to its end is
    still a request.

    ``event`` matters because a stop or verify event legitimately has no prompt
    text, and calling that "unknown" would put it in the same bucket as a prompt
    whose text we failed to read -- one is the normal shape of a session event
    and the other is a capture defect, and they must stay distinguishable.
    """
    payload = payload or {}
    t = text or ""
    head = t[:600]
    if event not in ("prompt",) and not t.strip():
        return Provenance(PROV_SESSION, f"a {event} event carries no request text")
    # An explicit parent/agent in the payload beats any text heuristic.
    if payload.get("parent_session_id") or payload.get("parent_tool_use_id") \
            or payload.get("agent_type") or payload.get("subagent_type"):
        return Provenance(PROV_WORKER,
                          "the payload names a parent session or agent type")
    if _NOTIFICATION.search(head):
        return Provenance(PROV_NOTIFICATION,
                          "the text opens with <task-notification>")
    if _REMINDER.search(head) and not _CONTINUATION.search(t):
        return Provenance(PROV_REMINDER, "the text opens with <system-reminder>")
    if _CONTINUATION.search(head):
        return Provenance(PROV_CONTINUATION,
                          "the text opens with a continuation or compaction preamble")
    if _LOCAL_CMD.search(head):
        return Provenance(PROV_REMINDER,
                          "the text opens with a local-command envelope")
    if not t.strip():
        return Provenance(PROV_UNKNOWN, "empty text and no parent in the payload")
    return Provenance(PROV_USER, "no harness envelope at the start of the text")


def notification_task_ids(text: str) -> list[str]:
    """The background-task ids a notification names. These identify the JOB, not
    the originating request, which is why they are recorded beside the link
    rather than used as it."""
    return re.findall(r"<task-id>\s*([A-Za-z0-9_-]+)\s*</task-id>", text or "")


# ------------------------------------------------------------ thread linking

def _read_threads(home: Path) -> dict[str, Any]:
    p = home / THREADS_FILE
    try:
        return cast(dict[str, Any], json.loads(p.read_text(encoding="utf-8")))
    except Exception:
        return {}


def _write_threads(home: Path, d: dict[str, Any]) -> None:
    p = home / THREADS_FILE
    try:
        p.parent.mkdir(parents=True, exist_ok=True)
        tmp = p.with_suffix(".tmp")
        tmp.write_text(json.dumps(d, sort_keys=True), encoding="utf-8")
        tmp.replace(p)
    except Exception:
        pass


def _read_jobs(home: Path) -> dict[str, Any]:
    try:
        return cast(dict[str, Any], json.loads((home / JOBS_FILE).read_text(encoding="utf-8")))
    except Exception:
        return {}


def _write_jobs(home: Path, d: dict[str, Any]) -> None:
    try:
        p = home / JOBS_FILE
        p.parent.mkdir(parents=True, exist_ok=True)
        tmp = p.with_suffix(".tmp")
        tmp.write_text(json.dumps(d, sort_keys=True), encoding="utf-8")
        tmp.replace(p)
    except Exception:
        pass


def link(home: Path, *, session_id: str, event_id: str, prov: Provenance,
         job_ids: list[str] | None = None) -> Provenance:
    """Attach the task thread this event belongs to, and say how confidently.

    A `user_request` or `worker_assignment` **is** its own origin:
    `attribution = "self"`.

    Everything else INHERITS the session's open thread, and that inheritance is
    **an association heuristic, not established ownership.** The case that makes
    it one: a `<task-notification>` announces a background job that may have been
    STARTED under an earlier task, while the session has since moved on to a new
    request. Assigning it to the currently open thread would then attribute a
    change set to work that did not cause it.

    So the job ledger records which thread first saw each job id. When a
    notification names a job whose first sighting was under a DIFFERENT thread,
    the record keeps both candidates and sets `ownership_uncertain`, rather than
    silently picking one. Uncertainty is retained; it is not resolved by guessing.
    """
    threads = _read_threads(home)
    cur = threads.get(session_id) or {}
    if prov.kind in (PROV_USER, PROV_WORKER):
        prov.originating_event_id = event_id
        prov.task_id = event_id
        prov.attribution = ATTR_SELF
        prov.attribution_basis = "the event is its own originating request"
        threads[session_id] = {"task_id": event_id, "opened_at": _now(),
                               "kind": prov.kind}
        _write_threads(home, threads)
        return prov

    open_task = cur.get("task_id")
    prov.task_id = open_task
    prov.originating_event_id = open_task
    prov.attribution = ATTR_HEURISTIC
    prov.attribution_basis = "the session's open thread at the time of the event"

    # A named background job may predate the open thread.
    if job_ids:
        jobs = _read_jobs(home)
        earlier: list[str] = []
        changed = False
        for jid in job_ids:
            rec = jobs.get(jid)
            if rec is None:
                jobs[jid] = {"first_seen_task_id": open_task, "first_seen_at": _now(),
                             "sessions": [session_id]}
                changed = True
                continue
            first = rec.get("first_seen_task_id")
            if first and open_task and first != open_task:
                earlier.append(str(first))
            if session_id not in (rec.get("sessions") or []):
                rec.setdefault("sessions", []).append(session_id)
                changed = True
        if changed:
            _write_jobs(home, jobs)
        if earlier:
            cands = sorted({*earlier, *( [open_task] if open_task else [] )})
            prov.ownership_uncertain = True
            prov.candidate_task_ids = cands
            prov.attribution_basis = (
                "the session's open thread, BUT a named job was first seen under "
                "a different thread; ownership is not established")
    return prov


# ------------------------------------------------------------------ snapshot

def _is_text(b: bytes) -> bool:
    return b"\0" not in b[:8192]


def _blob_path(home: Path, sha: str) -> Path:
    return home / BLOBS_DIR / sha[:2] / sha


def put_blob(home: Path, data: bytes) -> str:
    sha = hashlib.sha256(data).hexdigest()
    p = _blob_path(home, sha)
    try:
        if not p.exists():
            p.parent.mkdir(parents=True, exist_ok=True)
            tmp = p.with_name(p.name + ".tmp")
            tmp.write_bytes(data)
            tmp.replace(p)
    except Exception:
        return sha          # the hash is still a valid reference to report
    return sha


def get_blob(home: Path, sha: str) -> bytes | None:
    try:
        return _blob_path(home, sha).read_bytes()
    except Exception:
        return None


@dataclass
class Snapshot:
    """The working tree as the assistant could see it: tracked modifications and
    untracked files, by content, not by commit."""
    repo: str | None
    head: str | None
    branch: str | None
    files: dict[str, dict[str, Any]] = field(default_factory=dict)
    skipped: list[dict[str, str]] = field(default_factory=list)
    truncated: bool = False
    clean: bool = True
    wall_s: float = 0.0

    @property
    def manifest_sha256(self) -> str:
        body = "\n".join(f"{k} {v.get('status','')} {v.get('sha256','')}"
                         for k, v in sorted(self.files.items()))
        return hashlib.sha256(body.encode("utf-8")).hexdigest()

    def to_dict(self) -> dict[str, Any]:
        return {"repo": self.repo,
                "head": self.head, "head_role": "storage_reference",
                "branch": self.branch,
                "manifest_sha256": self.manifest_sha256,
                "files": self.files, "skipped": self.skipped,
                "truncated": self.truncated, "clean": self.clean,
                "file_count": len(self.files),
                "bytes": sum(int(v.get("bytes") or 0) for v in self.files.values()),
                "wall_s": round(self.wall_s, 3)}


def _git(repo: Path, *args: str, timeout: float = 5.0) -> str:
    # git writes paths as the bytes it has; decoded as UTF-8 with the
    # undecodable byte kept (surrogateescape), never the console's codec,
    # which on Windows is a single-byte page that cannot spell them
    try:
        return subprocess.run(["git", "-C", str(repo), *args], capture_output=True,
                              text=True, encoding="utf-8", errors="surrogateescape",
                              timeout=timeout).stdout
    except Exception:
        return ""


def _status_entries(repo: Path) -> list[tuple[str, str]]:
    """(status, path) for every changed file, from the NUL-separated form.

    The line form C-quotes any path outside ASCII ("caf\\303\\251.txt"), and a
    parser that strips the quotes then looks the escaped spelling up on disk,
    finds nothing, and records the file as deleted. With -z there is no
    quoting; a rename or copy carries its origin as a second field, dropped
    here because the destination is what exists."""
    parts = _git(repo, "status", "--porcelain", "-uall", "-z").split("\0")
    entries: list[tuple[str, str]] = []
    i = 0
    while i < len(parts):
        rec = parts[i]
        i += 1
        if len(rec) < 4:
            continue
        xy, rel = rec[:2], rec[3:]
        if "R" in xy or "C" in xy:
            i += 1                              # the origin path; not a file of the tree
        entries.append((xy.strip(), rel))
    return entries


def snapshot(cwd: Path, home: Path, *, deadline_s: float = SNAPSHOT_DEADLINE_S) -> Snapshot:
    """The pre- or post-state of one working tree, content-addressed.

    Bounded on four axes and every bound is recorded when it bites, because the
    difference between "the workspace was small" and "we stopped looking" is the
    difference between evidence and a guess.
    """
    t0 = time.monotonic()
    from .tasks import repository_root
    repo = repository_root(cwd)
    if repo is None:
        s = Snapshot(repo=None, head=None, branch=None)
        s.wall_s = time.monotonic() - t0
        s.skipped.append({"path": str(cwd), "why": "not a git repository"})
        return s
    head = _git(repo, "rev-parse", "HEAD").strip() or None
    branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD").strip() or None
    s = Snapshot(repo=str(repo), head=head, branch=branch)
    # --porcelain respects .gitignore; -uall so a new file in a new directory is
    # seen individually rather than as a directory entry.
    total = 0
    for status, rel in _status_entries(repo):
        if time.monotonic() - t0 > deadline_s:
            s.truncated = True
            s.skipped.append({"path": "(remaining)", "why": f"snapshot deadline {deadline_s}s"})
            break
        if len(s.files) >= MAX_FILES:
            s.truncated = True
            s.skipped.append({"path": rel, "why": f"over {MAX_FILES} changed files"})
            continue
        p = repo / rel
        entry: dict[str, Any] = {"status": status}
        if p.is_symlink():
            # a link is a path, and git stores it as one: reading through it
            # would copy whatever it points at, inside the repository or
            # not, into the blob store. The target is the content.
            try:
                target = os.readlink(p)
            except OSError:
                s.skipped.append({"path": rel, "why": "cannot read link"})
                continue
            entry["symlink"] = target
            entry["sha256"] = hashlib.sha256(target.encode("utf-8", "surrogateescape")).hexdigest()
            entry["blob"] = False
            s.skipped.append({"path": rel, "why": "symlink, target recorded not followed"})
            s.files[rel] = entry
            continue
        if status == "D" or not p.exists():
            entry["deleted"] = True
            s.files[rel] = entry
            continue
        try:
            size = p.stat().st_size
        except Exception:
            s.skipped.append({"path": rel, "why": "cannot stat"})
            continue
        entry["bytes"] = size
        if size > MAX_FILE_BYTES:
            entry["sha256"] = _sha_file(p)
            entry["blob"] = False
            s.skipped.append({"path": rel, "why": f"over {MAX_FILE_BYTES} bytes, hashed not stored"})
            s.files[rel] = entry
            continue
        if total + size > MAX_TOTAL_BYTES:
            entry["sha256"] = _sha_file(p)
            entry["blob"] = False
            s.truncated = True
            s.skipped.append({"path": rel, "why": f"snapshot total would exceed {MAX_TOTAL_BYTES} bytes"})
            s.files[rel] = entry
            continue
        try:
            data = p.read_bytes()
        except Exception:
            s.skipped.append({"path": rel, "why": "cannot read"})
            continue
        entry["sha256"] = hashlib.sha256(data).hexdigest()
        if _is_text(data):
            put_blob(home, data)
            entry["blob"] = True
        else:
            entry["blob"] = False
            entry["binary"] = True
            s.skipped.append({"path": rel, "why": "binary, hashed not stored"})
        total += size
        s.files[rel] = entry
    s.clean = not s.files
    s.wall_s = time.monotonic() - t0
    return s


def snapshot_all(cwd: Path, home: Path, *,
                 deadline_s: float = SNAPSHOT_DEADLINE_S) -> dict[str, Any]:
    """Every repository at or under ``cwd``, snapshotted.

    Necessary and not a refinement: sessions here run from an umbrella directory
    with the real projects as untracked checkouts inside it, so a snapshot of the
    cwd's own repository sees the nested repos as one untracked entry and records
    **none** of the work done in them. v1 already handled that for commit heads
    via ``repos_under``; a state snapshot needs it for the same reason and more
    urgently, because a missing head can be recovered and a missing pre-state
    cannot.

    The deadline is shared across repositories rather than per repository, so a
    session started somewhere with many checkouts degrades by recording fewer
    repositories -- and saying so -- instead of by blowing the hook's budget.
    """
    from .tasks import repos_under

    t0 = time.monotonic()
    repos: dict[str, Any] = {}
    skipped: list[dict[str, str]] = []
    try:
        found = repos_under(Path(cwd))
    except Exception:
        found = []
    if not found:
        found = [Path(cwd)]
    for repo in found:
        left = deadline_s - (time.monotonic() - t0)
        if left <= 0.2:
            skipped.append({"path": str(repo), "why": "shared snapshot deadline spent"})
            continue
        snap = snapshot(Path(repo), home, deadline_s=left)
        repos[str(repo)] = snap.to_dict()
    body = "\n".join(f"{k} {v.get('manifest_sha256','')}" for k, v in sorted(repos.items()))
    return {"repos": repos,
            "repos_skipped": skipped,
            "combined_sha256": hashlib.sha256(body.encode("utf-8")).hexdigest(),
            "repo_count": len(repos),
            "file_count": sum(int(v.get("file_count") or 0) for v in repos.values()),
            "bytes": sum(int(v.get("bytes") or 0) for v in repos.values()),
            "truncated": any(v.get("truncated") for v in repos.values()) or bool(skipped),
            "clean": all(v.get("clean") for v in repos.values()) if repos else True,
            "wall_s": round(time.monotonic() - t0, 3)}


def change_set_all(before: dict[str, Any] | None,
                   after: dict[str, Any] | None) -> dict[str, Any]:
    """The complete resulting change set across every snapshotted repository."""
    b = (before or {}).get("repos") or {}
    a = (after or {}).get("repos") or {}
    per: dict[str, Any] = {}
    total = 0
    for repo in sorted(set(a) | set(b)):
        cs = change_set(b.get(repo) or {}, a.get(repo) or {})
        if cs["count"]:
            per[repo] = cs
            total += cs["count"]
    return {"per_repo": per, "count": total,
            "repos_touched": sorted(per),
            "paths": sorted(f"{r}/{p}" for r, cs in per.items() for p in cs["paths"])}


def _sha_file(p: Path) -> str:
    h = hashlib.sha256()
    try:
        with p.open("rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                h.update(chunk)
    except Exception:
        return ""
    return h.hexdigest()


def change_set(before: Snapshot | dict[str, Any], after: Snapshot | dict[str, Any]) -> dict[str, Any]:
    """The complete resulting change set between two snapshots, including
    dirty-to-dirty edits a commit range cannot express."""
    b = before.files if isinstance(before, Snapshot) else (before or {}).get("files") or {}
    a = after.files if isinstance(after, Snapshot) else (after or {}).get("files") or {}
    added = sorted(k for k in a if k not in b)
    removed = sorted(k for k in b if k not in a)
    changed = sorted(k for k in set(a) & set(b)
                     if a[k].get("sha256") != b[k].get("sha256"))
    return {"added": added, "removed": removed, "modified": changed,
            "paths": sorted(set(added) | set(removed) | set(changed)),
            "count": len(set(added) | set(removed) | set(changed))}


# ------------------------------------------------------------------- records

def _now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def new_event_id() -> str:
    return f"{int(time.time() * 1000):013d}-{uuid.uuid4().hex[:12]}"


def identity(payload: dict[str, Any], *, session_id: str) -> dict[str, Any]:
    """Parent/worker identity, explicit, and absent when the harness does not
    supply it rather than inferred. A guessed parent is worse than a null one:
    it would silently reattribute a worker's change set."""
    parent = (payload.get("parent_session_id") or payload.get("parent_tool_use_id")
              or payload.get("parent_id") or None)
    agent = payload.get("agent_type") or payload.get("subagent_type") or None
    return {"session_id": session_id,
            "parent_session_id": parent,
            "agent": agent,
            "worker": bool(parent or agent),
            "transcript_path": payload.get("transcript_path"),
            "tool_use_id": payload.get("tool_use_id"),
            "harness_event": payload.get("hook_event_name")}


def completeness(rec: dict[str, Any]) -> dict[str, Any]:
    """Which of the fields a learning method needs this record actually has.

    Reported per record so "capture completeness" is a number rather than an
    impression, and so a method's training eligibility can be computed without
    re-deriving what counts.
    """
    st = rec.get("state") or {}
    ws = st.get("workspace") or {}
    if "repos" in ws:                      # the multi-repository shape
        repos = ws.get("repos") or {}
        files = [f for v in repos.values() for f in (v.get("files") or {}).values()]
        ws = {"manifest_sha256": ws.get("combined_sha256"),
              "files": {str(i): f for i, f in enumerate(files)},
              "truncated": ws.get("truncated"),
              "head": any(v.get("head") for v in repos.values())}
    return {
        "raw_payload": bool(rec.get("raw")),
        "provenance_labelled": bool((rec.get("provenance") or {}).get("kind")),
        "linked_to_task": bool((rec.get("provenance") or {}).get("task_id")),
        "attribution_established": (rec.get("provenance") or {}).get("attribution") == ATTR_SELF,
        "parent_worker_explicit": (rec.get("identity") or {}).get("worker") is not None,
        "pre_or_post_state": bool(ws.get("manifest_sha256")),
        "state_contents_stored": any(f.get("blob") for f in (ws.get("files") or {}).values()),
        "state_complete": bool(ws) and not ws.get("truncated", False),
        "commit_head": bool(ws.get("head")),
        "model_interaction": bool((rec.get("identity") or {}).get("transcript_path")),
        "verification": bool(rec.get("verification")),
    }


def build(event: str, *, payload: dict[str, Any], cwd: Path, home: Path,
          tool: str = "", session_id: str = "",
          snap: Snapshot | dict[str, Any] | None = None,
          verification: dict[str, Any] | None = None) -> dict[str, Any]:
    """One capture record. Raw payload preserved, provenance labelled, thread
    linked, state attached, completeness computed."""
    eid = new_event_id()
    text = str(payload.get("prompt") or payload.get("message") or "")
    prov = classify(text, payload=payload, event=event)
    jobs = notification_task_ids(text)
    prov = link(home, session_id=session_id, event_id=eid, prov=prov, job_ids=jobs)
    raw = payload
    blob = json.dumps(payload, sort_keys=True, default=str)
    raw_ref = None
    if len(blob) > MAX_RAW_BYTES:
        # Preserved, not truncated away: the full payload goes to the blob store
        # and the record keeps a reference plus a head for reading.
        raw_ref = put_blob(home, blob.encode("utf-8"))
        raw = {"_truncated": True, "_blob_sha256": raw_ref,
               "_bytes": len(blob), "_head": blob[:4096]}
    rec: dict[str, Any] = {
        "schema": SCHEMA, "event_id": eid, "event": event, "timestamp": _now(),
        "tool": tool, "session_id": session_id, "cwd": str(cwd),
        "raw": raw,
        "provenance": prov.to_dict(),
        "notification_task_ids": jobs,
        "identity": identity(payload, session_id=session_id),
        "state": {"workspace": (snap.to_dict() if isinstance(snap, Snapshot) else snap)},
        "verification": verification,
    }
    rec["completeness"] = completeness(rec)
    return rec


def append(home: Path, rec: dict[str, Any], *, path: Path | None = None) -> Path:
    p = path or (home / CAPTURE2_FILE)
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("a", encoding="utf-8") as f:
        f.write(json.dumps(rec, sort_keys=True, default=str) + "\n")
    return p


# --------------------------------------------------------------- verification

# The runner must BEGIN a command, not merely appear in one. An earlier version
# used a bare word match and accepted `echo pytest-ish`, which would have stapled
# a meaningless exit code to a workspace state. Commands begin at the start of
# the string or after a shell separator, optionally behind env assignments.
_CMD_START = r"(?:\A|[;&|]{1,2}\s*|\n)\s*(?:[A-Za-z_][A-Za-z0-9_]*=\S*\s+)*"
_TEST_CMD = re.compile(
    _CMD_START + r"(?:pytest|py\.test|python[0-9.]*\s+-m\s+pytest|"
    r"make\s+(?:test|check)|go\s+test|cargo\s+test|"
    r"npm\s+(?:run\s+)?test|pnpm\s+test|yarn\s+test|tox|nox)(?:\s|\Z)")


def looks_like_verification(command: str) -> bool:
    """Whether a shell command is a verification run.

    Deliberately a whitelist of test runners rather than anything that could be
    one. A false positive attaches a meaningless exit code to a state and makes
    the verification field untrustworthy, which is worse than a missing one.
    """
    return bool(_TEST_CMD.search(command or ""))


_EMBEDDED_EXEC_COMMAND = re.compile(
    r"\b(?:tools\.)?exec_command\s*\(\s*\{[^{}]{0,1024}?"
    r"\b(?:cmd|command)\s*:\s*(\"(?:\\.|[^\"\\])*\")", re.DOTALL)


def verification_io(payload: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    """Normalize direct shell and Codex unified-exec verification payloads.

    Codex CLI exposes a shell command directly. Some Codex surfaces wrap the
    same call in a JavaScript ``exec`` tool whose input has a ``code`` string;
    only a quoted ``cmd``/``command`` property is admitted from that wrapper.
    The extracted text still has to pass ``looks_like_verification``.
    """
    tool_input = payload.get("tool_input") or {}
    command = ""
    if isinstance(tool_input, dict):
        command = str(tool_input.get("command") or tool_input.get("cmd") or "")
        code = tool_input.get("code")
        if not command and isinstance(code, str):
            for match in _EMBEDDED_EXEC_COMMAND.finditer(code):
                try:
                    candidate = json.loads(match.group(1))
                except ValueError:
                    continue
                if isinstance(candidate, str) and looks_like_verification(candidate):
                    command = candidate
                    break
    tool_response = payload.get("tool_response") or {}
    if not isinstance(tool_response, dict):
        tool_response = {"output": str(tool_response)}
    return command, tool_response


def verification_record(*, command: str, exit_code: int | None, output_tail: str,
                        manifest_sha256: str, cwd: str) -> dict[str, Any]:
    """A verification BOUND to the state it ran against.

    The manifest hash is the binding. Without it a recorded exit code says only
    that some tests passed at some point in the session, which is not evidence
    about any particular change set.
    """
    return {"command": command, "exit_code": exit_code,
            "verdict": {0: "passed", 1: "failed"}.get(exit_code if exit_code is not None else -1),
            "output_tail": (output_tail or "")[-2000:],
            "bound_to_manifest_sha256": manifest_sha256,
            "cwd": cwd, "at": _now()}
