// One generation: prompt, sampling loop, constraints, KV reuse.
#ifndef RUNNER_ENGINE_H
#define RUNNER_ENGINE_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "model.h"
#include "tokenizer.h"
#include "sample.h"
#include "schema.h"
#include "jsonmode.h"

// return nonzero to abort generation (e.g. client disconnected)
typedef int (*gen_cb)(void *ud, const char *bytes, int n);

// Forced-close budget: the transition sentence plus the close token. Sized
// for a byte-fallback vocabulary, where a short English sentence can cost one
// token per byte (the CI fixture spells the default line in 50-odd tokens
// where a real vocabulary spends a dozen). A sentence that does not fit is
// never truncated: half a sentence in the model's voice is worse than none,
// so a caller's is refused at the request and the built-in default falls
// back to the bare close.
#define THINK_FORCE_MAX 256

typedef struct { int32_t id; float lp; } lp_alt; // logprob alternative

// JC-R1 constrained-choice posterior: one DECISION POINT — a constrained
// sampling step where >= 2 of the probed top candidates were legal under
// the active schema/JSON constraint. prob[] is the softmax renormalized
// over the legal probed set (raw logits, temperature-free); coverage is
// the full-softmax mass of everything probed, so a consumer can see how
// much distribution the probe examined. Alternatives beyond CL_MAX_ALT
// count toward n_legal/renormalization but are not stored.
#define CL_MAX_ALT 8
typedef struct {
    int32_t pos;                 // emitted-token index in this generation
    int32_t n_legal;             // legal candidates among the probed set
    float   coverage;            // full-softmax mass of ALL probed candidates
    int32_t ids[CL_MAX_ALT];     // legal alternatives, descending probability
    float   prob[CL_MAX_ALT];    // renormalized over the legal probed set
    float   raw_lp[CL_MAX_ALT];  // full-vocab log-softmax of each
} cl_rec;

typedef struct {
    model_t   *m;
    tokenizer *tok;
    sampler   *smp;
    int  pos;              // next free KV slot
    int  stop_ids[12];
    int  n_stop;
    // Stop ids the REQUEST added: a stop string that spells a control token
    // exactly, or stop_token_ids. Live for one request; completion_cleanup
    // clears them. Control tokens decode to no bytes, so the text matcher
    // could never see `<|eom|>`; these end the turn on the id itself.
    int  req_stop_ids[8];
    int  n_req_stop;
    bool ignore_eos;
    bool hit_stop;         // last generate ended on a stop token / json done
    // The terminator the last generate ended on, when it ended on a TOKEN
    // (an engine stop id or a request stop id): its vocabulary id, else -1
    // (stop string, budget, constraint close, no legal continuation). The
    // server reports it beside finish_reason, since "stop" alone cannot tell
    // Muse's <|eom|> from its <|eot|> (lab finding 2026-09-22).
    int  stop_id;
    // Request opt-in (completions `special_tokens`): a control token that is
    // not a stop renders as its vocabulary spelling to the callback and the
    // logprob tables instead of decoding to nothing. Never under a
    // constraint; the validator's byte stream stays the decoded one.
    bool render_special;
    bool oom;              // generation aborted on an allocation failure — the
                           // finish reason is "error", never a silent "stop"
    bool json_mode;        // constrain output to a single JSON object
    const snode *schema;   // constrain output to a JSON schema (overrides json_mode)
    // Constrained mode hides the thinking prelude from the output callback by
    // default (a raw completion's contract is "constrained payload only").
    // Chat serving sets this so the prelude reaches the callback too, where
    // the server's thinking-tag splitter routes it to the reasoning channel —
    // without it, a thinking model's schema call that exhausts max_tokens
    // mid-think returns empty content AND empty reasoning: undiagnosable.
    bool emit_think_prelude;
    // Native Harmony schemas include their own channel/reasoning prelude;
    // constrain from the first generated byte instead of probing for the
    // model family's ordinary think markers outside the schema.
    bool constraint_includes_prelude;
    sval  sv;
    jsonv jv;
    // The constrained payload exactly as it was fed to sv/jv, so the validator
    // can be re-seated on any PREFIX of it (engine_constraint_truncate). Only
    // the real engine records: the sample-lookahead copies below are shallow,
    // and a copy that appended here would realloc the original's buffer out
    // from under it. Lives for one generation; see cdoc_release.
    char *cdoc; int cdoc_n, cdoc_cap;
    bool  cdoc_rec;
    // True while the generation callback is receiving the engine's synthesized
    // closing tail rather than the model's output. A sink that filters model
    // text — a client `stop` sequence is the one that exists — must pass this
    // through untouched: it is the server completing a truncated document to
    // something legal, and the bytes that do that are exactly the ones an
    // ordinary stop (`}`, `"\n\n"`) matches.
    bool  constraint_closing;
    // Set only on the shallow engine copies constraint_token_ok makes to test
    // a candidate token. It says "this engine is already a throwaway", which
    // lets the constraint layer feed the validators in place instead of
    // through a second copy of its own: a rejected token cannot leave a
    // half-consumed validator behind when the whole engine is discarded a
    // line later. Never true on an engine anyone reads afterwards.
    bool  constraint_scratch;
    // constrained thinking-tag prelude: probe for think_open, sample freely
    // through think_close, then enforce sv/jv and emit only the payload
    uint8_t constraint_phase;
    bool    constraint_tag_possible;
    int     constraint_tag_match, constraint_close_match;
    int     think_end_id;       // Muse <|eom|>: decoded-empty reasoning close
    int     prelude_max, prelude_count;
    // R4.12.16 reasoning budget (budget forcing, s1-style). A distilled
    // student can state its answer in the first sentence of a reasoning turn
    // and then hedge for hundreds of tokens without ever closing it (the lab
    // measured 3.4x the parent's reasoning length on Kvist-14B, 2 turns in 17
    // never closing at all). With think_budget > 0, once a turn's cumulative
    // REASONING tokens reach it the sampler is restricted to the model's
    // reasoning-close token, so the turn closes and the model addresses its
    // next recipient normally. Counted per request across every reasoning
    // turn in it, so a model that closes and immediately re-opens gets no
    // second budget. Never a stop: the answer still runs to max_tokens.
    // Needs a model whose reasoning close is a single token (think_end_id).
    int     think_budget;    // 0 = off
    int     think_tokens;    // reasoning tokens this request
    bool    think_on;        // inside a reasoning turn right now
    bool    think_forcing;   // the forced close is being emitted
    bool    think_forced;    // the budget fired at least once (telemetry)
    int     think_open_match, think_close_match;
    // What the forced close emits, token by token: an optional transition
    // sentence in the model's own voice, then the reasoning-close token.
    // The sentence is not decoration. A bare terminator drops a model mid
    // sentence and measurably costs accuracy on the answer that follows
    // (llama.cpp's own budget PR reports HumanEval 93% uncapped, ~89% capped
    // with a message, 79% capped with a bare end tag on Qwen3.5-9B; s1
    // 2501.19393 and Qwen3's "Considering the limited time..." use the same
    // pattern), so runner defaults to a short neutral one and lets a caller
    //replace it or ask for the bare close with an empty string.
    int32_t think_force[THINK_FORCE_MAX];
    int     think_force_n, think_force_at;
    // the request's transition sentence, tokenized once at request setup
    int32_t think_msg[THINK_FORCE_MAX - 1];
    int     think_msg_n;
    bool    prelude_exhausted;
    bool progress;         // print prompt progress to stderr
    int32_t *hist;         // tokens whose KV occupies slots [0, pos)
    // What the last engine_rewind / engine_prefix_reuse did with the slot's
    // previous state (a rewind_how value), and the recurrent turn mark's
    // binding: the fold in the model's mark buffers was taken over hist[0,
    // mark_pos), whose FNV-1a hash this is. Belt and braces over the
    // structural rule (the mark is dropped whenever pos moves below it).
    int      rewind_how;
    uint64_t mark_hash;
    // optional per-token logprob capture (server "logprobs"): caller points
    // these at buffers sized [lp_cap] / [lp_cap * lp_n] before generating
    float   *lp_chosen;    // chosen-token logprob per emitted token
    int32_t *lp_ids;       // chosen token id per emitted token
    lp_alt  *lp_top;       // top-N alternatives per token
    int      lp_n, lp_cap, lp_count;
    // JC-R1 "choice_logprobs": constrained-choice posteriors. When cl_cap>0
    // and a schema/JSON constraint is active, each payload sampling step
    // probes the top cl_probe candidates by raw logit against the validator
    // and records a decision point when >= 2 are legal — the renormalized
    // posterior over the legal set is the calibrated verdict surface the
    // judgment co-processor reads (suite docs/plans/judgment-coprocessor.md).
    cl_rec  *cl_recs;      // caller-owned buffer [cl_cap]
    int      cl_cap, cl_count, cl_probe;
    // speculative decoding: a small draft model proposes draft_k tokens per
    // round, the target verifies them in one batched forward
    model_t *dm;           // draft model (NULL = off)
    int      dpos;         // draft KV position (may trail pos)
    int      draft_k;      // drafts per round
    // NextN/MTP head drafts: no draft model; the target's own predictor
    // block proposes draft_k tokens per round (model_mtp_* in model.h).
    // The engine feeds the head every token the target consumes, so the
    // head's KV always covers hist[0..pos).
    bool     mtp_on;
    // Prompt-lookup drafts (--draft-lookup): no weights, no draft forward.
    // Each round the last n context tokens are searched for in the context
    // itself (prompt plus everything generated so far) and the tokens that
    // followed their most recent earlier occurrence are proposed, up to
    // draft_k; no match proposes nothing, so that round costs one search.
    // Exclusive with dm and mtp_on (one draft source per run); grammar
    // fast-forward still preempts it under a constraint, as it does the
    // others. See engine_lookup_draft.
    bool     lookup_on;
    // JC-R2 grammar fast-forward: when the active constraint pins a unique
    // byte continuation, its tokenization is drafted for free (no draft
    // forwards) and verified by the target exactly like a draft-model
    // proposal, so output stays sampler-identical to plain decoding.
    // Opt-in via RUNNER_GRAMMAR_FF=1 (see engine_init for the measured
    // reason); needs the batched verify path (not full GPU offload).
    bool     gram_ff;
    struct { int rounds, drafted, accepted,      // all drafts (every source)
                 gr_drafted, gr_accepted,        // grammar-pinned drafts only
                 lk_drafted, lk_accepted; }      // prompt-lookup drafts only
             spec_st;                            // reset per generation
    // JC-R2 Phase 0 trace (RUNNER_GRAMMAR_TRACE=path): the current grammar
    // round's pinned bytes + drafted ids, stashed at draft time and emitted
    // as one JSONL record when the verify walk resolves the round. Slot-safe
    // (per-engine, not file-static) because --serve runs parallel slots.
    char     gtr_pin[96];  // pinned bytes (GRAM_FF_BYTES)
    int      gtr_plen;
    int32_t  gtr_d[16];    // drafted ids (SPEC_DRAFT_MAX)
    int      gtr_nd;
    // in-flight generation budget, owned by engine_gen_begin/step/end
    int      gen_max, gen_count;
    // KV row engine_gen_step handed out for the caller to forward, -1 when
    // none is outstanding; see engine_gen_end.
    int      pending_pos;
    double   gen_t0;
    // yielded between prefill chunks (see engine_set_prefill_yield)
    void (*prefill_yield)(void *ud);
    void *prefill_ud;
    // request cancellation, sampled only at complete prefill/decode steps
    bool (*stop)(void *ud);
    void *stop_ud;
    // identity of everything that decides what this engine's KV bytes mean:
    // the weights, the geometry, the tokenizer and the cache element type.
    // Computed once by engine_init; see engine_prefix_reuse.
    uint64_t model_key;
} engine;

// Called between prefill chunks so a caller holding the device turn can drop
// it and let someone else in.
//
// Prefill is the longest single thing a slot does, and it used to hold that
// turn for all of it: measured on Qwen2.5-7B, a short request arriving during
// a 2,300-token prefill waited 26.2 s against 0.237 s alone -- 110x, i.e. the
// whole prefill. engine_feed already walks the prompt in n_batch chunks, so
// the fix is to let the caller yield between them; the hold becomes one chunk
// instead of one prompt.
//
// Unset is a no-op: the CLI, and any server without a scheduler running.
void engine_set_prefill_yield(engine *e, void (*yield)(void *ud), void *ud);

// Install a request-scoped cancellation predicate. It is sampled between
// complete prefill chunks and decode steps, never inside a model forward.
// Unset is a no-op.
void engine_set_stop(engine *e, bool (*stop)(void *ud), void *ud);

// True when this request should take the speculative walk (a draft model,
// the MTP head, the prompt lookup, and/or grammar fast-forward under an
// active constraint): shared by engine_generate and the server's scheduler
// dispatch so they cannot drift.
bool engine_wants_spec(const engine *e);

// The prompt-lookup search, the whole of the fourth draft source. `hist` is
// the context so far, hist[len-1] the token whose successors are wanted.
// For n from ENGINE_LOOKUP_N_MAX down to ENGINE_LOOKUP_N_MIN, find the MOST
// RECENT earlier occurrence of the last n tokens (an occurrence may overlap
// the suffix, which is what a run of repeats looks like) and copy the k
// tokens that followed it into `out`: the context after the occurrence,
// then, past the context end, the proposal's own period (a match P tokens
// back means the context has repeated with period P since, and the guess
// is that it keeps doing so). The longest n that matches wins; returns k,
// or 0 when nothing matched. Pure: no allocation, no state, O(len * n)
// integer compares per call. Pinned against hand-computed proposals in
// tests/test_lookup_draft.c.
// N_MIN=3 by measurement (SmolLM2-135M, 2026-09-04): 2-gram matches were
// mostly spurious (an unrelated prompt drafted 24 tokens and had 1 accepted;
// at 3 it drafted 4), and each wrong draft is a wasted verify column, while
// the input-grounded rows kept their drafts (99% and 80% acceptance).
enum { ENGINE_LOOKUP_N_MIN = 3, ENGINE_LOOKUP_N_MAX = 5 };
int engine_lookup_draft(const int32_t *hist, int len, int k, int32_t *out);

// Returns false if the per-context history buffer could not be allocated;
// the caller must not use the engine in that case.
bool   engine_init(engine *e, model_t *m, tokenizer *tok, sampler *smp);
void   engine_reset(engine *e); // clear KV position + sampler + json state
void   engine_think_started(engine *e); // prompt already contains think_open
// Reasoning budget only: read the prompt's reasoning state (the last
// think_open/think_close wins) so a raw completion that resumes an open
// reasoning turn is counted from its first generated token.
void   engine_think_budget_prime(engine *e, const char *prompt);
// keep the KV for the longest common prefix of hist and toks, reset the rest
// of the engine state; returns how many prompt tokens can be skipped
int    engine_rewind(engine *e, const int32_t *toks, int n);
// What engine_rewind (or the prefix fork after it) did with the slot's
// previous state; engine_rewind_how_name spells it for the request telemetry
// (runner_telemetry.timing.cache) and the start line, so a client that sees
// "0 cached" on a prompt it just sent can read WHY instead of guessing.
enum rewind_how {
    REWIND_NONE = 0,   // cache off or a fresh slot: nothing to keep
    REWIND_EXTENDED,   // the prompt extends the slot's history verbatim
    REWIND_KV,         // attention rows [0, keep) kept, the tail re-fed
    REWIND_SNAPSHOT,   // recurrent fold restored from the exact snapshot at keep
    REWIND_MARK,       // recurrent fold resumed at the turn mark, tail re-fed
    REWIND_RECURRENT,  // recurrent fold not restorable at keep: recomputed from 0
    REWIND_RING,       // KV ring: any rewind recomputes from 0
    REWIND_MISMATCH,   // the prompt differs from history at its first token
    REWIND_FORK,       // forked from the shared prefix cache (engine_prefix_reuse)
};
const char *engine_rewind_how_name(int how);
// Recurrent turn mark (model_recurrent_mark): checkpoint the fold at the
// slot's current position, the prompt boundary of the request being served,
// so the NEXT request on this slot can resume there. An agent client's next
// prompt replays this one, the reply re-rendered by the template, then a new
// turn: the kept run ends where the re-rendering first differs, past the
// prompt but short of e->pos, where no exact snapshot exists, and before
// the mark a recurrent slot re-folded the whole prompt on every turn.
// engine_rewind resumes from the mark whenever the kept run reaches it.
// false = not a recurrent model (nothing to mark) or the mark failed.
bool   engine_mark_turn(engine *e);
// The request's own stop ids (engine.req_stop_ids): up to 8, replaced whole;
// n = 0 clears them.
void   engine_set_request_stops(engine *e, const int *ids, int n);
// feed tokens (batched); returns last-token logits, or NULL on overflow/stop
float *engine_feed(engine *e, const int32_t *toks, int n);
// sample until stop/limit, streaming decoded bytes to cb; returns token count
int    engine_generate(engine *e, float *logits, int max_new,
                       gen_cb cb, void *ud, double *gen_time);

// The same generation, one step at a time, for a caller that owns the forward.
//
// Continuous batching needs the forward hoisted out of the loop: one thread
// must issue every model_batch_decode, while the sampler, schema validator,
// stop check, logprob capture and streaming callback stay per-sequence and run
// wherever the caller likes. Splitting engine_generate at that seam — rather
// than writing a second batched generation loop — is what keeps a batched
// request's output identical to a solo one by construction.
//
//   engine_gen_begin(e, max_new);
//   while (engine_gen_step(e, logits, cb, ud, &tok, &pos) == ENGINE_STEP_MORE)
//       logits = <forward tok at pos, batched or not>;
//   n = engine_gen_end(e, cb, ud, &secs);
//
// A caller that abandons the loop early (deadline, cancellation) must still
// call engine_gen_end: that is where a truncated constrained document is
// closed to something valid, and where the KV row of the forward that never
// happened is given back. engine_gen_step counts *next_pos as occupied the
// moment it hands it over — everything downstream reads e->pos as "rows
// [0, pos) hold KV computed from hist[0, pos)" — so a step whose forward is
// abandoned must not leave that row claimed, or the next request's
// engine_rewind keeps a row nobody ever wrote.
enum { ENGINE_STEP_DONE = 0, ENGINE_STEP_MORE = 1 };
// Discard the last `n` bytes of the constrained document, as if the model had
// never generated them, and returns how many were actually discarded.
//
// A sink that does not deliver everything the engine handed it — a client
// `stop` sequence drops the matched bytes and whatever was held behind them —
// leaves the validator AHEAD of the document the client received, and the
// closing tail engine_gen_end synthesizes then continues a state nobody has.
// Reporting the shortfall here re-seats the validator on exactly the delivered
// prefix, so the closer completes the client's copy instead of the engine's.
//
// The truncation point is a byte offset, not a token or a node boundary: it may
// land mid-token, inside a string, or between an object's members. All three
// are ordinary validator states, because the payload is replayed from its start
// and the validator is a byte machine — there is no un-feed, and none is needed.
//
// Call it before engine_gen_end (or before engine_generate returns, i.e. from
// the generation callback itself); afterwards the document is gone.
int    engine_constraint_truncate(engine *e, int n);

void   engine_gen_begin(engine *e, int max_new);
int    engine_gen_step(engine *e, const float *logits, gen_cb cb, void *ud,
                       int32_t *next_tok, int *next_pos);
int    engine_gen_end(engine *e, gen_cb cb, void *ud, double *gen_time);
// load a draft model for speculative decoding (shared by CLI and server);
// see engine.c for the gates. NULL = speculation could not be enabled.
model_t *spec_draft_load(const char *path, const model_t *target,
                         const model_params *mp);
double now_s(void);

//
// engine_rewind reuses the KV a slot happens to still hold from its own last
// request. This is the same idea made durable and shareable: a completed
// prefix is snapshotted out of a slot's KV cache into host memory, and any
// slot serving a compatible model can fork it back in. Agent traffic is what
// pays for it — every request in a session repeats the same system prompt,
// tool list and schema verbatim, and that block is usually most of the prompt.
//
// Two calls, in the order a request meets them:
//
//   prefix_reuse r = engine_prefix_reuse(e, toks, n);   // before prefill
//   logits = engine_feed(e, toks + r.keep, n - r.keep);
//   engine_prefix_publish(e, toks, n, r.keep, prefill_seconds); // after
//
// There is deliberately no "look up" / "install" pair: installing a prefix
// that does not match the prompt is the one failure mode that produces a
// plausible wrong answer instead of an error, so the decision and the install
// are one operation that never sees a token vector it did not itself compare.
typedef struct {
    int    keep;     // prompt tokens whose KV is in place; feed from here
    int    forked;   // of those, tokens installed from a shared snapshot
    double saved_s;  // prefill seconds those forked tokens would have cost,
                     // priced at this process's measured seconds-per-token
} prefix_reuse;
prefix_reuse engine_prefix_reuse(engine *e, const int32_t *toks, int n);
// Offer the KV now occupying [0, n) for future forks. fed is how many of those
// tokens this request actually prefilled and prefill_s how long that took;
// together they price future hits. Cheap and safe to call unconditionally.
void engine_prefix_publish(engine *e, const int32_t *toks, int n,
                           int fed, double prefill_s);

typedef struct {
    uint64_t hits, misses, stores, evictions;
    uint64_t tokens_reused;
    double   saved_prefill_s;   // cumulative, same pricing as prefix_reuse
    double   cost_per_token_s;  // measured prefill cost behind that figure
    size_t   bytes, budget;
    int      entries;
    double   ttl;
} prefix_cache_stats;

// budget 0 disables the shared cache (each slot's own rewind is unaffected);
// ttl_s is how long an unused snapshot survives.
void   prefix_cache_configure(size_t budget_bytes, double ttl_s);
void   prefix_cache_stats_get(prefix_cache_stats *out);
void   prefix_cache_clear(void);
// host bytes one n-token snapshot of this model would occupy
size_t prefix_cache_entry_bytes(const model_t *m, int n);

// ---- snapshot persistence (runner.prefix.v1) --------------------------
//
// A warm prefix cache is worth minutes of prefill and it dies with the
// process. These write it to a file and read it back, so a restarted server
// answers the first agent request at fork speed instead of prefill speed.
//
// The trust question is the whole design. A snapshot is raw KV bytes: loading
// one that does not belong to this model does not error, it produces a
// confident wrong answer, which is the single failure mode this cache's
// lookup path was built to avoid. So the file carries the engine's
// `model_key` -- which already binds the weights, the geometry, the tokenizer,
// the context length and the KV element type -- and every entry whose key does
// not match the live engine is refused, not adapted. The file is also checked
// for a magic, a version, a length-consistent body and a payload digest before
// any of it is believed; a truncated or edited file loads nothing.
//
// It is opt-in and explicit. There is no default path and no automatic
// discovery: a cache directory that another user can write is a way to hand
// this process someone else's KV, and the way not to have that problem is not
// to go looking for files nobody asked for.
//
// Returns the number of entries written / loaded, or -1 on an I/O or format
// error (with a reason on stderr). Loading is additive and skips anything that
// does not fit the live budget.
int prefix_cache_save(const char *path);
int prefix_cache_load(const char *path, const engine *e);

#endif // RUNNER_ENGINE_H
