// Generated from kernels_tensor.metal — do not edit.
static const char *k_metal_tensor_src =
    "// Metal 4 / M5 tensor-op prefill tracer bullet. Compiled as a separate\n"
    "// library so an unavailable MPP compiler can only remove this optional rung.\n"
    "#include <metal_stdlib>\n"
    "#include <metal_tensor>\n"
    "#include <MetalPerformancePrimitives/MetalPerformancePrimitives.h>\n"
    "using namespace metal;\n"
    "\n"
    "struct mm_args {\n"
    "    int n_in, n_out, n_col;\n"
    "    ulong w_off;\n"
    "    int has_bias, x_stride, y_stride;\n"
    "};\n"
    "\n"
    "static inline void get_scale_min_k4(int j, device const uchar *q,\n"
    "                                    thread uchar *d, thread uchar *m) {\n"
    "    if (j < 4) {\n"
    "        *d = q[j] & 63;\n"
    "        *m = q[j + 4] & 63;\n"
    "    } else {\n"
    "        *d = (q[j + 4] & 0xF) | ((q[j - 4] >> 6) << 4);\n"
    "        *m = (q[j + 4] >> 4)  | ((q[j    ] >> 6) << 4);\n"
    "    }\n"
    "}\n"
    "\n"
    "// out[col][row] = sum_k x[col][k] * W[row][k]. Each type's dequantization\n"
    "// is intentionally identical to its k_mm_* twin; only the matrix primitive\n"
    "// changes. DEQ16 fills dstw[0..15] with weights kg..kg+15 of row\n"
    "// (row0+row); every other line of the kernel is shared verbatim.\n"
    "#define TENSOR_KERNEL(NAME, DEQ16) \\\n"
    "kernel void NAME( \\\n"
    "        device const uchar *wb   [[buffer(0)]], \\\n"
    "        device float       *x    [[buffer(1)]], \\\n"
    "        device float       *y    [[buffer(2)]], \\\n"
    "        constant mm_args   &a    [[buffer(3)]], \\\n"
    "        device const float *bias [[buffer(4)]], \\\n"
    "        threadgroup half *shmem  [[threadgroup(0)]], \\\n"
    "        uint2 tgpig [[threadgroup_position_in_grid]], \\\n"
    "        ushort tid [[thread_index_in_threadgroup]]) { \\\n"
    "    constexpr int TM = 128, TN = 256, TK = 64, NT = 128; \\\n"
    "    const int row0 = (int)tgpig.x * TM; \\\n"
    "    const int col0 = (int)tgpig.y * TN; \\\n"
    "    threadgroup half *tw = shmem; \\\n"
    " \\\n"
    "    auto w_full = tensor(tw, dextents<int32_t, 2>(TK, TM)); \\\n"
    "    auto x_full = tensor(x, dextents<int32_t, 2>(a.n_in, a.n_col), \\\n"
    "                         array<int, 2>({1, a.x_stride})); \\\n"
    "    mpp::tensor_ops::matmul2d< \\\n"
    "        mpp::tensor_ops::matmul2d_descriptor( \\\n"
    "            TN, TM, static_cast<int>(dynamic_extent), false, true, true, \\\n"
    "            mpp::tensor_ops::matmul2d_descriptor::mode::multiply_accumulate), \\\n"
    "        execution_simdgroups<4>> mm; \\\n"
    "    auto out = mm.get_destination_cooperative_tensor<decltype(x_full), \\\n"
    "                                                       decltype(w_full), float>(); \\\n"
    " \\\n"
    "    for (int k0 = 0; k0 < a.n_in; k0 += TK) { \\\n"
    "        for (int work = tid; work < TM * (TK / 16); work += NT) { \\\n"
    "            int row = work / (TK / 16), chunk = work % (TK / 16); \\\n"
    "            int kg = k0 + chunk * 16; \\\n"
    "            threadgroup half *dstw = tw + row * TK + chunk * 16; \\\n"
    "            if (row0 + row < a.n_out) { \\\n"
    "                DEQ16 \\\n"
    "            } else { \\\n"
    "                for (int j = 0; j < 16; j++) dstw[j] = 0.0h; \\\n"
    "            } \\\n"
    "        } \\\n"
    "        threadgroup_barrier(mem_flags::mem_threadgroup); \\\n"
    "        auto w_tile = tensor(tw, dextents<int32_t, 2>(TK, TM)); \\\n"
    "        auto x_tile = tensor(x + k0 + (ulong)col0 * a.x_stride, \\\n"
    "                             dextents<int32_t, 2>(TK, a.n_col - col0), \\\n"
    "                             array<int, 2>({1, a.x_stride})); \\\n"
    "        mm.run(x_tile, w_tile, out); \\\n"
    "        threadgroup_barrier(mem_flags::mem_threadgroup); \\\n"
    "    } \\\n"
    " \\\n"
    "    auto dst = tensor(y, dextents<int32_t, 2>(a.y_stride, a.n_col), \\\n"
    "                      array<int, 2>({1, a.y_stride})); \\\n"
    "    out.store(dst.slice(row0, col0)); \\\n"
    "    threadgroup_barrier(mem_flags::mem_device); \\\n"
    "    if (a.has_bias) { \\\n"
    "        for (int i = tid; i < TM * TN; i += NT) { \\\n"
    "            int col = i / TM, row = i % TM; \\\n"
    "            if (col0 + col < a.n_col && row0 + row < a.n_out) \\\n"
    "                y[(ulong)(col0 + col) * a.y_stride + row0 + row] += bias[row0 + row]; \\\n"
    "        } \\\n"
    "    } \\\n"
    "}\n"
    "\n"
    "\n"
    "#define TENSOR_DEQ_Q4_K \\\n"
    "                int nsb = a.n_in / 256; \\\n"
    "                int sb = kg / 256, j32 = (kg % 256) / 32; \\\n"
    "                device const uchar *blk = wb + a.w_off \\\n"
    "                    + ((ulong)(row0 + row) * nsb + sb) * 144; \\\n"
    "                float dall = (float)*(device const half *)blk; \\\n"
    "                float dmin = (float)*(device const half *)(blk + 2); \\\n"
    "                uchar scale, minv; \\\n"
    "                get_scale_min_k4(j32, blk + 4, &scale, &minv); \\\n"
    "                device const uchar *q = blk + 16 + (j32 / 2) * 32; \\\n"
    "                int lane0 = kg & 31; \\\n"
    "                for (int j = 0; j < 16; j++) { \\\n"
    "                    int quant = (j32 & 1) ? (int)(q[lane0 + j] >> 4) \\\n"
    "                                          : (int)(q[lane0 + j] & 0xF); \\\n"
    "                    dstw[j] = (half)(dall * (float)scale * (float)quant \\\n"
    "                                   - dmin * (float)minv); \\\n"
    "                }\n"
    "\n"
    "#define TENSOR_DEQ_Q8_0 \\\n"
    "                int nb = a.n_in / 32; \\\n"
    "                int bi = kg / 32, off = kg % 32; \\\n"
    "                device const uchar *blk = wb + a.w_off \\\n"
    "                    + ((ulong)(row0 + row) * nb + bi) * 34; \\\n"
    "                float d = (float)*(device const half *)blk; \\\n"
    "                device const char *q = (device const char *)(blk + 2) + off; \\\n"
    "                for (int j = 0; j < 16; j++) \\\n"
    "                    dstw[j] = (half)(d * (float)q[j]);\n"
    "\n"
    "#define TENSOR_DEQ_Q4_0 \\\n"
    "                int nb = a.n_in / 32; \\\n"
    "                int bi = kg / 32, off = kg % 32; \\\n"
    "                device const uchar *blk = wb + a.w_off \\\n"
    "                    + ((ulong)(row0 + row) * nb + bi) * 18; \\\n"
    "                float d = (float)*(device const half *)blk; \\\n"
    "                device const uchar *q = blk + 2; \\\n"
    "                for (int j = 0; j < 16; j++) { \\\n"
    "                    int v = off ? (int)(q[j] >> 4) : (int)(q[j] & 0xF); \\\n"
    "                    dstw[j] = (half)(d * (float)(v - 8)); \\\n"
    "                }\n"
    "\n"
    "TENSOR_KERNEL(k_tensor_q4_K, TENSOR_DEQ_Q4_K)\n"
    "TENSOR_KERNEL(k_tensor_q8_0, TENSOR_DEQ_Q8_0)\n"
    "TENSOR_KERNEL(k_tensor_q4_0, TENSOR_DEQ_Q4_0)\n"
    "\n"
;
static const char *k_metal_tensor_sha = "39143174814da42723a918e360f1a01b6dfb4710a072b39580ccea3542bf8b7b";
